### ISSUE TITLE
Error in TCPSocket

### ISSUE THREAD

**Issue by RedstoneAlmeida** [TransendStudios/Trinket#2]
I do not know what could be

![image](https://cloud.githubusercontent.com/assets/15146680/26178933/f7ae3e98-3b36-11e7-86db-f58a8e1631f4.png)

**Comment by ImagicalGamer** [comment]
hmm, Im running it directly out of PyCharm. I'll look for the issue.

**Comment by ImagicalGamer** [comment]
Try now

**Comment by ImagicalGamer** [comment]
Just tested on Windows and it works, should be fine on Linux.
