### ISSUE TITLE
Need a website?

### ISSUE THREAD

**Issue by remotevase** [TransendStudios/Trinket#3]

**Comment by remotevase** [comment]
@ImagicalGamer @AppleDevelops

**Comment by ImagicalGamer** [comment]
@remotevase idk lol

**Comment by remotevase** [comment]
i'll make you one anyways to make it seem a little bit more proffesional

**Comment by remotevase** [comment]
Hey, can I be a contributer? it would be easier to commit directly to the gh-pages branch

**Comment by ImagicalGamer** [comment]
Sure @remotevase
