### ISSUE TITLE
Bug Tracking

### ISSUE THREAD

**Issue by RedstoneAlmeida** [TransendStudios/Trinket#7]

**Comment by RedstoneAlmeida** [comment]
*Fixed BUG* in: https://github.com/TransendStudios/Trinket/commit/817eeab332261f06dab012f3fef7bd00c0241120

*new bug*: 
![image](https://cloud.githubusercontent.com/assets/15146680/26250356/2028c47a-3c80-11e7-87b6-65c1239098e8.png)

**Comment by ImagicalGamer** [comment]
It's JSON encoded, you must decode it with JSON as well

**Comment by ImagicalGamer** [comment]
I cant recreate this error.

**Comment by ImagicalGamer** [comment]
Why UTF-8 decode? The client doesn't encode them. Only encoded when sent from Python.

**Comment by ImagicalGamer** [comment]
This is only happening on your branch, its because of the UFT-8 decode.

**Comment by RedstoneAlmeida** [comment]
I tried to find a solution, and that was the best I found

**Comment by RedstoneAlmeida** [comment]
The errors, were before decoding in UTF8

**Comment by ImagicalGamer** [comment]
Try the master branch.

**Comment by ImagicalGamer** [comment]
The TypeError is from decoding.

**Comment by RedstoneAlmeida** [comment]
I'll try, but the master branch was what I was using, along with TrinketPM

**Comment by ImagicalGamer** [comment]
Weird, I did find a bug with the mater branch thanks to the errors on the other branch.

**Comment by RedstoneAlmeida** [comment]
Similar bug?

**Comment by ImagicalGamer** [comment]
No, an error was thrown when a client force disconnected on windows (ctrl + c) and then the server tried sending a disconnect packet.

**Comment by RedstoneAlmeida** [comment]
I'll try to recreate this bug here.

**Comment by RedstoneAlmeida** [comment]
Is the bug in the main branch or branch I created?

**Comment by ImagicalGamer** [comment]
The bug you showed a pic of was on the branch you created.

**Comment by ImagicalGamer** [comment]
What packet was being sent when that error was thrown?

**Comment by RedstoneAlmeida** [comment]
![image](https://cloud.githubusercontent.com/assets/15146680/26265295/fab2e180-3cb6-11e7-80b1-60c40773e8eb.png)
master branch

**Comment by RedstoneAlmeida** [comment]
First and second photo were from the main branch, now the third photo was from my branch, after trying to fix the bug

**Comment by ImagicalGamer** [comment]
change it to json.loads(conn.read(1024).decode().strip())

**Comment by ImagicalGamer** [comment]
conn.recv()

**Comment by ImagicalGamer** [comment]
I'm making a commit now...

**Comment by RedstoneAlmeida** [comment]
okay

**Comment by ImagicalGamer** [comment]
Try using 4a8ac0ead76cc40a272c1ea96ee08bff569513d3

**Comment by RedstoneAlmeida** [comment]
no erros, working :)

**Comment by ImagicalGamer** [comment]
Awesome.

**Comment by RedstoneAlmeida** [comment]
All because of a decode, incredible lmao

**Comment by ImagicalGamer** [comment]
Yep

**Comment by ImagicalGamer** [comment]
Python converts everything to bytes for some reason.

**Comment by ImagicalGamer** [comment]
With PHP you can send a JSON string through a socket.

**Comment by RedstoneAlmeida** [comment]
Yes, it's even easier, but python transforms into bytes and has to be converted back.

**Comment by ImagicalGamer** [comment]
I'm working on error reporting, the backtrace will be uploaded to paste.ubuntu.com and then sent to our API.

**Comment by RedstoneAlmeida** [comment]
Bug in CTRL + C and Reconnect

![image](https://cloud.githubusercontent.com/assets/15146680/26265907/6bf76972-3cb9-11e7-81aa-d1da40cadf15.png)

**Comment by ImagicalGamer** [comment]
Wait 6 seconds before reconnecting and see if it still throws the KeyError

**Comment by ImagicalGamer** [comment]
nvm I found the problem

**Comment by RedstoneAlmeida** [comment]
found?

**Comment by ImagicalGamer** [comment]
Fixed in c52d210afa285c062444b4da286a5f314ce19589

**Comment by RedstoneAlmeida** [comment]
Fixed =)


![image](https://cloud.githubusercontent.com/assets/15146680/26266099/48ad3d9c-3cba-11e7-8dfe-9ad1d6cd568a.png)

**Comment by ImagicalGamer** [comment]
Awesome.

**Comment by RedstoneAlmeida** [comment]
Fixed =)


![image](https://cloud.githubusercontent.com/assets/15146680/26266099/48ad3d9c-3cba-11e7-8dfe-9ad1d6cd568a.png)

**Comment by RedstoneAlmeida** [comment]
I'm looking for other bugs, I want to do a test to transfer information

**Comment by ImagicalGamer** [comment]
Alright, delete the connectionfixes branch and create a dev branch and commit to it with new stuff. Only commit bug fixes to master branch.

**Comment by ImagicalGamer** [comment]
Use 'Dump' branch for dev commits.

**Comment by RedstoneAlmeida** [comment]
I already did this, I created a branch called dump, to put some print to discover more errors

**Comment by ImagicalGamer** [comment]
I'm busy this weekend (have to work) so I won't be that active Tomorrow morning - afternoon or all day Sunday.

**Comment by RedstoneAlmeida** [comment]
I'll see what I can do in your absence, I'll look for some bugs.

**Comment by RedstoneAlmeida** [comment]
Working Server Chat to Trinket Host

![image](https://cloud.githubusercontent.com/assets/15146680/26266665/b6115236-3cbc-11e7-9289-f5f7d7555eb1.png)

**Comment by ImagicalGamer** [comment]
Awesome.

**Comment by ImagicalGamer** [comment]
I'm gonna add you to the org so you can push updates to TrinketPM.

**Comment by RedstoneAlmeida** [comment]
Ok, thanks

**Comment by ImagicalGamer** [comment]
I want to make this similar to bungee cord.

**Comment by ImagicalGamer** [comment]
@RedstoneAlmeida have you added what you wanted to the 'Dump' branch? I want to merge it into master so I can finish a few new things.

**Comment by ImagicalGamer** [comment]
Why are you encoding the data parameter of ServerInformationPacket? PHP json_encode encodes it all and json.dumps() decodes everything.

**Comment by RedstoneAlmeida** [comment]
I'm coding, because when I send direct without encoding, Trinket does not read, for example dataJson ["name"] it ends up not reading when it is not coded, for this I am coding, it reads straight.

**Comment by RedstoneAlmeida** [comment]
![image](https://cloud.githubusercontent.com/assets/15146680/26278622/81f32baa-3d75-11e7-9074-1f64008be17c.png)

**Comment by ImagicalGamer** [comment]
Okay

**Comment by ImagicalGamer** [comment]
Ready to merge it?

**Comment by RedstoneAlmeida** [comment]
Here from Dump to Master Yes, it's ready, just need to change something in TrinketPM, I changed the json from ServerName to ServerID in QueryRegenerateEvent

**Comment by ImagicalGamer** [comment]
Okay

**Comment by RedstoneAlmeida** [comment]
Do you think the ServerInformation packet is good? I found it useful to transfer information to the trinket

**Comment by ImagicalGamer** [comment]
Yes I think it will be useful.

**Comment by ImagicalGamer** [comment]
Whoops didnt mean to merge new-commands into master branch but no conflicts so not a huge deal.

**Comment by RedstoneAlmeida** [comment]
I do not understand, is there a branch new commands? I had not noticed lmao

**Comment by ImagicalGamer** [comment]
There was for about 5 seconds, there is an error in master branch of TrinketPM. I'm about to fix it in my next commit so don't bother with it.

**Comment by RedstoneAlmeida** [comment]
okay

**Comment by RedstoneAlmeida** [comment]
Hey, why not make a system of "cache" in Trinket? To store information coming from the ServerInformationPacket, to be able to take information from other servers connected to the Trinket

**Comment by ImagicalGamer** [comment]
Im doing it now :)

**Comment by RedstoneAlmeida** [comment]
:)

**Comment by ImagicalGamer** [comment]
Check latest commit, both new commands on TrinketPM work correctly. When the client logs into trinket the data is default {"online": 0} because no players or anything can connect during the login time.

**Comment by RedstoneAlmeida** [comment]
ok

**Comment by RedstoneAlmeida** [comment]
is working correctly

**Comment by ImagicalGamer** [comment]
Yes everything works correctly, Im writing the docs for packets and stuff on the wiki

**Comment by RedstoneAlmeida** [comment]
okay

**Comment by RedstoneAlmeida** [comment]
I have the idea of facilitating an encrypted pass-through, from one server to another, if there is more than one main lobby, instead of using Mysql to log in, thus bringing a faster processing and no loss and locking

**Comment by ImagicalGamer** [comment]
We don't use MySQL? Passwords do need to be encrypted before they are sent to the server.

**Comment by RedstoneAlmeida** [comment]
Stored inside the Trinket Host, and then fetched by the server in the trinket

**Comment by ImagicalGamer** [comment]
We shouldn't cache sensitive data.

**Comment by ImagicalGamer** [comment]
Or allow servers to access it.

**Comment by RedstoneAlmeida** [comment]
Not in the form of cache, but as a "mysql" only easier to save, and exclusive know?

**Comment by ImagicalGamer** [comment]
Why would we need to? The password is saved in settings.json.

**Comment by ImagicalGamer** [comment]
Do you mean player passwords?

**Comment by ImagicalGamer** [comment]
I'm working on data for when a player is transferred to a new server, if you meant player passwords we can use the SimpleAuth API to authenticate them on login if they came from a connected server.

**Comment by RedstoneAlmeida** [comment]
Yes, the passwords of the players, but this may be in a future extension of the trinket, just wanted to say an idea

**Comment by ImagicalGamer** [comment]
I get what you mean, I'll do that now.

**Comment by RedstoneAlmeida** [comment]
Okay, if you need help you can call here or on twitter.

**Comment by ImagicalGamer** [comment]
We need to parse the address and port of PlayerTransferEvent into a serverID to check if connected to trinket

**Comment by RedstoneAlmeida** [comment]
After it logs on to a server, it could send a data to the saved trinket, and when it switches server look for the nickname in the trinket whether it is connected or not

**Comment by ImagicalGamer** [comment]
I have an idea for it...

**Comment by ImagicalGamer** [comment]
TransferInformationPacket with player name, address and port of server they are transferring to and the current timestamp. Trinket will process and ip and port and check if its a connected client and then send that data to the new server, the server decodes the data and then when the player joins they are authed.

**Comment by ImagicalGamer** [comment]
It's gonna have to be rlly fast since the player connects to the new server in a matter of milliseconds.

**Comment by ImagicalGamer** [comment]
Gonna clear some older messages in this issue, it takes too long to scroll to the bottom :)

**Comment by RedstoneAlmeida** [comment]
ASyncTask can facilitate this, I think ..

**Comment by ImagicalGamer** [comment]
I made the first transfer commit to the transfer branch. No new packet required, adding an entry type to ServerInformationPacket. TrinketPM will probs need some new storage classes.

**Comment by ImagicalGamer** [comment]
The packet is being sent directly not being added to the send queue in TrinketPM.

**Comment by RedstoneAlmeida** [comment]
The packet is being sent directly not being added to the send queue in TrinketPM.

**Comment by ImagicalGamer** [comment]
It does work.

**Comment by ImagicalGamer** [comment]
I intended to send it directly, if its in the queue it could be a few seconds before the packet is sent and that would make the transfer packet useless.

**Comment by ImagicalGamer** [comment]
It has to be sent before the player connects to the new server so it needs to be sent directly.

**Comment by RedstoneAlmeida** [comment]
Can be sent later to authenticate, because only after it enters the server of the to compare the data

**Comment by ImagicalGamer** [comment]
The server will cache the transfer data so when the player connects they are auto authed.

**Comment by RedstoneAlmeida** [comment]
I understood, I think I would have to do it after entering the server myself.

**Comment by RedstoneAlmeida** [comment]
Testing the chat packet, correcting some errors and testing the communication, I think everything is working correctly

![image](https://cloud.githubusercontent.com/assets/15146680/26284381/fbc77bd0-3e0f-11e7-9199-bcaa04d00f41.png)

**Comment by ImagicalGamer** [comment]
When I get back tomorrow I'll parse MC color into terminal colors.

**Comment by RedstoneAlmeida** [comment]
okay

**Comment by ImagicalGamer** [comment]
@RedstoneAlmeida what to add? Trinket isn't that useful.

**Comment by RedstoneAlmeida** [comment]
Is very similar to a Bungee, because it does not make a transfer system between servers, with a packet request
